const sectors = [
    {name: "Manufacturing"},
    {name: "Construction materials"},
    {name: "Electronics and Optics"},
    {name: "Food and Beverage"},
    {name: "Bakery & confectionery products"},
    {name: "Beverages"},
    {name: "Fish & fish products"},
    {name: "Meat & meat products"},
    {name: "Milk & dairy products"},
    {name: "Other"},
    {name: "Sweets & snack food"},
    {name: "Furniture"},
    {name: "Bathroom/sauna"},
    {name: "Bedroom"},
    {name: "Children’s room"},
    {name: "Kitchen"},
    {name: "Living room"},
    {name: "Office"},
    {name: "Other (Furniture)"},
    {name: "Outdoor"},
    {name: "Project furniture"},
    {name: "Machinery"},
    {name: "Machinery components"},
    {name: "Machinery equipment/tools"},
    {name: "Manufacture of machinery"},
    {name: "Maritime"},
    {name: "Aluminium and steel workboats"},
    {name: "Boat/Yacht building"},
    {name: "Ship repair and conversion"},
    {name: "Metal structures"},
    {name: "Other"},
    {name: "Repair and maintenance service"},
    {name: "Metalworking"},
    {name: "Construction of metal structures"},
    {name: "Houses and buildings"},
    {name: "Metal products"},
    {name: "Metal works"},
    {name: "CNC-machining"},
    {name: "Forgings, Fasteners"},
    {name: "Gas, Plasma, Laser cutting"},
    {name: "MIG, TIG, Aluminum welding"},
    {name: "Plastic and Rubber"},
    {name: "Packaging"},
    {name: "Plastic goods"},
    {name: "Plastic processing technology"},
    {name: "Blowing"},
    {name: "Moulding"},
    {name: "Plastics welding and processing"},
    {name: "Plastic profiles"},
    {name: "Printing"},
    {name: "Advertising"},
    {name: "Book/Periodicals printing"},
    {name: "Labelling and packaging printing"},
    {name: "Textile and Clothing"},
    {name: "Clothing"},
    {name: "Textile"},
    {name: "Wood"},
    {name: "Other (Wood)"},
    {name: "Wooden building materials"},
    {name: "Wooden houses"},
    {name: "Other"},
    {name: "Creative industries"},
    {name: "Energy technology"},
    {name: "Environment"},
    {name: "Service"},
    {name: "Business services"},
    {name: "Engineering"},
    {name: "Information Technology and Telecommunications"},
    {name: "Data processing, Web portals, E-marketing"},
    {name: "Programming, Consultancy"},
    {name: "Software, Hardware"},
    {name: "Telecommunications"},
    {name: "Tourism"},
    {name: "Translation services"},
    {name: "Transport and Logistics"},
    {name: "Air"},
    {name: "Rail"},
    {name: "Road"},
    {name: "Water"}
];

export default sectors;