export const GET_ALL_SECTORS_REQUEST = 'GET_ALL_SECTORS_REQUEST';
export const GET_ALL_SECTORS_SUCCESS = 'GET_ALL_SECTORS_SUCCESS';
export const GET_ALL_SECTORS_FAIL = 'GET_ALL_SECTORS_FAIL';

export const SECTOR_LIST_DATA_REQUEST = 'SECTOR_LIST_DATA_REQUEST';
export const SECTOR_LIST_DATA_SUCCESS = 'SECTOR_LIST_DATA_SUCCESS';
export const SECTOR_LIST_DATA_FAIL = 'SECTOR_LIST_DATA_FAIL';

export const SECTOR_DETAILS_REQUEST = 'SECTOR_DETAILS_REQUEST';
export const SECTOR_DETAILS_SUCCESS = 'SECTOR_DETAILS_SUCCESS';
export const SECTOR_DETAILS_FAIL = 'SECTOR_DETAILS_FAIL';

export const SECTOR_DELETE_REQUEST = 'SECTOR_DELETE_REQUEST';
export const SECTOR_DELETE_SUCCESS = 'SECTOR_DELETE_SUCCESS';
export const SECTOR_DELETE_FAIL = 'SECTOR_DELETE_FAIL';

export const SECTOR_CREATE_REQUEST = 'SECTOR_CREATE_REQUEST';
export const SECTOR_CREATE_SUCCESS = 'SECTOR_CREATE_SUCCESS';
export const SECTOR_CREATE_FAIL = 'SECTOR_CREATE_FAIL';
export const SECTOR_CREATE_RESET = 'SECTOR_CREATE_RESET';

export const SECTOR_UPDATE_REQUEST = 'SECTOR_UPDATE_REQUEST';
export const SECTOR_UPDATE_SUCCESS = 'SECTOR_UPDATE_SUCCESS';
export const SECTOR_UPDATE_FAIL = 'SECTOR_UPDATE_FAIL';
export const SECTOR_UPDATE_RESET = 'SECTOR_UPDATE_RESET';